### ISSUE TITLE
The table views on mobile are not responsive

### ISSUE THREAD

**Issue by mgorzanski** [fortedigital/Optimizely.ContentUsage#27]

**Comment by mgorzanski** [comment]
@Fifok @darekhalecki It's hard to fit all the columns on a mobile view. My suggestion is to add a horizontal scrollbar to the table, this is the only way to make sure that the columns are not squashed together and that they are readable. Is this a satisfying solution? 
See preview:
![image](https://user-images.githubusercontent.com/7347107/224998202-d015ea31-f9d6-4855-b404-b716fbc85b85.png)

**Comment by Fifok** [comment]
I think a horizontal scrollbar is a good solution.
