### ISSUE TITLE
Cleanup NuGet resources after NuGet is uninstalled

### ISSUE THREAD

**Issue by darekhalecki** [fortedigital/Optimizely.ContentUsage#47]
These should be removed from the Epi project.

![image](https://github.com/fortedigital/EpiContentUsage/assets/39534151/74356ef3-5fac-46f4-84cb-e62d5bbf0eab)

**Comment by Fifok** [comment]
It seems to be a correct behavior. When I installed Episerver.Find to a fresh Alloy project and after starting/initializing server a copy of Find.zip is created permamently. After removing NuGet for Find there is still this Find.zip.
